### ISSUE TITLE
Error: Not implemented: window.focus

### ISSUE THREAD

**Issue by teramotodaiki** [hackforplay/common#8]
```
Import as a module and initialize game

  1 test failed [19:03:31]Error: Not implemented: window.focus
    at module.exports (/Users/teramotodaiki/github/common/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
    at Window.focus (/Users/teramotodaiki/github/common/node_modules/jsdom/lib/jsdom/browser/Window.js:546:7)
    at Constructor.focus (/Users/teramotodaiki/github/common/src/hackforplay/hack.js:24:9)
    at Hack (/Users/teramotodaiki/github/common/test/index.js:35:2)
    at Test.callFn (/Users/teramotodaiki/github/common/node_modules/ava/lib/test.js:313:21)
    at Test.run (/Users/teramotodaiki/github/common/node_modules/ava/lib/test.js:326:23)
    at Runner.runSingle (/Users/teramotodaiki/github/common/node_modules/ava/lib/runner.js:257:19)
    at runHooks.then.hooksOk (/Users/teramotodaiki/github/common/node_modules/ava/lib/runner.js:317:16)

  1 test failed [19:03:51]
  1 unhandled rejection
  4 previous failures in test files that were not rerun
```

**Comment by cakeseller** [comment]
Hi. I'm having the same issue. Did you manage to resolve it?
